### ISSUE TITLE
Drop system

### ISSUE THREAD

**Issue by Eastrall** [Eastrall/Rhisis#160]
## Description

The drop system allow the player/monsters to place(drop) items on the map. A player can simply drag'n'drop an item from the inventory or a bag to the map to drop it and a monster drops items on the map when they die via the Battle System or a command.
There are three types of drops:

- Permenant drops (items dropped by a player)
- Temporary drops (items dropped by a monster when they die): These drops are linked to the player who killed the monster for some time. (time to define)
- Respawn drops (quest items)

**Note:** Gold is also considered as a dropped item.

## Roadmap

- [x] Create the `ItemEntity` that will reprensent an dropped item on the map
- [x] Create the `DropSystem` class
- [x] Create a permanent drop
- [x] Temporary drop
- [x] Respawn drop
- [x] Pick-up a drop (item or gold) (https://github.com/Eastrall/Rhisis/commit/f31862ecee70bb21cf062386e9c30e958aa2afac, https://github.com/Eastrall/Rhisis/commit/3f4eba25782a15b1fa372313fdac470e42314f16)
- [x] Player drop item from inventory (https://github.com/Eastrall/Rhisis/commit/fcb0fe617335a38bd227f49a1d519df8747551bb)
