### ISSUE TITLE
Customize system

### ISSUE THREAD

**Issue by Eastrall** [Eastrall/Rhisis#161]
## Description

FLYFF has a customization system that allows the player to change his hair style and select a new face. The system is triggered by NPC at Northern Flarine.
![image](https://user-images.githubusercontent.com/4021025/50601093-77010080-0eb3-11e9-9fee-b47c5a79d4e5.png)

More informations about the system here: http://flyff-wiki.webzen.com/wiki/Customizing

## Roadmap

- [x] Change hair style and color
- [x] Change face style
- [x] Remove gold from player
- [x] Use coupon

**Comment by Eastrall** [comment]
Implemented in PR #166 and #168
