### ISSUE TITLE
NPC Shop System

### ISSUE THREAD

**Issue by Eastrall** [Eastrall/Rhisis#25]
### Description

This system manages everything related with the npc shops.

This system should be able to load the NPC shops stored localy on the server. (We will use the JavaScript Object Notation (JSON) language to parse shops easily).

Once the resources are loaded and stored at the server startup, when the player requests for a shop, we should retrieve the shop corresponding to the NPC and then send it to the player.

### Roadmap

- [x] Define shop file structure
- [x] Load shops at server startup
- [x] NPC Shop System structure (`NotifiableSystemBase`)
- [x] Open a shop
- [x] Buy an item
- [x] Sell an item

**Comment by Eastrall** [comment]
Buy items is now available with PR : #55

**Comment by Eastrall** [comment]
Sell items available with PR #60
