### ISSUE TITLE
NPC Dialog System

### ISSUE THREAD

**Issue by Eastrall** [Eastrall/Rhisis#26]
### Description

This system is in charge of displaying NPC dialogs to the player. For example when the player clicks on a NPC, it should open the dialog box with the correct dialog. We should also handle the links like the "Introduction" or the "Farewell" links.

### Roadmap

- [x] General dialog file structure
- [x] Load dialogs
- [x] Receive open dialog request
- [x] Send correct dialog with links, etc...
- [x] NPC oral text

**Comment by Eastrall** [comment]
Open and display NPC dialog available with PR: #64

**Comment by Eastrall** [comment]
NPC Oral text added in PR: #81
