### ISSUE TITLE
Trade System

### ISSUE THREAD

**Issue by Eastrall** [Eastrall/Rhisis#27]
### Description

Manage an item trade between two players.
One of the two players sends a request for a trade to the target player. If the **target** accepts the request, then the trade window opens for both players.
Then each player can add/move/remove items in their containers.
When both players press the "OK" button then the trade is made.

⚠️ When the trade is completed, we need to check if the players have enough space in his inventory.

### Roadmap

- [x] Receive trade request and send it to the target player
- [x] Receive target's player answer
- [x] Send open trade window packet if target player accepts the trade request
- [x] Add[/Move/Remove] item from window (items needs to be visible for both players)
- [x] Swap items when both players have accepted the trade (+ verify space in inventory)
- [ ] Add trade packets structure to `docs/packets`

**Comment by Steve-Nzr** [comment]
Referenced in : #69
