### ISSUE TITLE
Death System

### ISSUE THREAD

**Issue by Eastrall** [Eastrall/Rhisis#30]
## Description

A player is declared "dead" when his HP (Hit Points) are less or equal than 0 (`player.Health.Hp <= 0`).
Once his dead, we should send a packet to every player around that the player has fallen in the ground.
Then, when the player resurects at lodelight, we should remove some experience and manage the experience and level loss.

## Roadmap

- [x] Load resurection zones (03a3bb2, 6886a3d)
- [x] Send death packet when player died. (03a3bb2)
- [x] Resurect to nearest revival region based on player's current position (d9d70a6)
- [x] Remove experience when player resurects to lodelight. (80fcb39)
