### ISSUE TITLE
Job System

### ISSUE THREAD

**Issue by Eastrall** [Eastrall/Rhisis#31]
## Description

The job system is one of the main systems of FLYFF. In fact, it allows the player to choose between several job classes like, magician, assist, acrobat and mercenary. Below, the FLYFF class tree:

![alt](https://i.imgur.com/B2mys4i.png)

You start the game as a Vagrant, then at level 15, you can choose between 4 classes. Once you are at level 60, each classes, has two possiblities.

## Roadmap

- [x] Load job data informations (56489ed)
- [x] Load jobs tree (aa78a80)
- [x] Prevent players from leveling up when reaching level 15 has a vagrant (56489ed)
- [x] Change job directly when talking to instructors. (56489ed)
