### ISSUE TITLE
Quest System

### ISSUE THREAD

**Issue by Eastrall** [Eastrall/Rhisis#32]
## Description

Quests are given by any other NPC in Madrigal and involve sub-stories where objectives are completed for rewards.

## Roadmap

- [x] Load quests (fd0242a, 259436a, 1412a35)
- [x] Add a `QuestEntity` to the `Rhisis.Database` project (c6fe467, 230d7c1)
- [x] Suggest quests to player (a27ac16)
- [x] Convert official quests to Lua quests
- [x] Accept quest
- [x] Update quests (based on quest configuration: Kill X monsters, go to some place, ect...)
- [x] Finish quest and give rewards (based on quest configuration: Gold, experience, ect...)
- [x] Load player diary
- [x] Save player diary
- [x] Check quest
