### ISSUE TITLE
Buff System

### ISSUE THREAD

**Issue by Eastrall** [Eastrall/Rhisis#348]
This system is related to the Skill System #35.

## Description

In FLYFF, there is some skills that gives bonuses to the players. These skills are also called buffs.

## Roadmap

- [ ] Cast bonus skill (buffs)
   - [ ] Create `DbSkillBonus` database entity
   - [ ] Apply bonuses to player (attack, speed, HP, MP, etc...)

**Comment by Eastrall** [comment]
Implemented in #472
