### ISSUE TITLE
Skill system

### ISSUE THREAD

**Issue by Eastrall** [Eastrall/Rhisis#35]
FLYFF has a skill tree system that allows the player to use abilities to fight monster by inflicting damages or give bonuses to itself or others.

More information about this system can be found here: http://flyff-wiki.webzen.com/wiki/Skills

## Roadmap

- [x] Load skills and skill levels (fb4db4d)
- [x] Create `DbSkill` database entity (19d9b3a)
- [x] Initialize player skills based on it's job (ba0e729)
- [x] Update skill with skill points (ebe28d6)
- [x] Save skills (7b0184d)
- [x]  Cast melee skill
- [x] Cast magic skill

**Comment by Eastrall** [comment]
System description and roadmap added.
