### ISSUE TITLE
Friend / Messenger system

### ISSUE THREAD

**Issue by Eastrall** [Eastrall/Rhisis#37]
## Description

In FLYFF, you have to possibility to play with other players and when we play with others, we usually make friends. The game offers the possibility to add friends and chat with them.

## Roadmap

- [x] Create `Friend` database entity
- [x] Load and send friends to the current player
- [x] Add a friend
- [x] Delete a friend
- [x] Block a friend
- [x] Set status
- [x] Send private messages

**Comment by Eastrall** [comment]
Roadmap added.

**Comment by MarkWilds** [comment]
Sign me up scotty!

**Comment by Eastrall** [comment]
Roadmap updated.
