### ISSUE TITLE
Rhisis Installer tool

### ISSUE THREAD

**Issue by Eastrall** [Eastrall/Rhisis#40]
### Description

This tools has to be made to make first setup and configuration easier. The tool has to check if the database exists and if it's the first database setup create the first admin account. Then, it will configure the Login, Cluster and World server.

### Roadmap

- [x] Use MahApps theme
- [x] Main Window
- [x] Database configuration
- [x] Database creation
- [x] Create first account
- [ ] Login Server configuration
- [ ] Cluster Server configuration
- [ ] World Server configuration

**Comment by DjTrilogic** [comment]
I can take the remaining tasks ;)
